Temp Filter Functions Module: Convert back to netstandard 2.0 (#3008)
For the dotnet upgrade, we made two changes to the filter functions module:
1. Updated SDK.Functions version from 1.0.26 to 3.0.5. Version 3.0.5 has a dependency on netcoreapp3.0 (not netcoreapp3.1) and does not function properly on linux arm32.
2. Published the module as an application rather than a lib

In the current setup on master branch, when the temp filter functions is ran on linux arm32 with version 3.0.5 it results in this stack trace:
```
info: Host.Startup[0]
      Generating 1 job function(s)
fail: Host.Startup[0]
      Error indexing method 'EdgeHubTrigger-CSharp'
Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexingException: Error indexing method 'EdgeHubTrigger-CSharp' ---> Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry. ---> DotNetty.Transport.Channels.ClosedChannelException: I/O error occurred.
   at DotNetty.Transport.Bootstrapping.Bootstrap.DoResolveAndConnectAsync(EndPoint remoteAddress, EndPoint localAddress)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.<>c__DisplayClass84_0.<<CreateChannelFactory>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsyncInternal(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass23_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass33_0.<<OpenAsyncInternal>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass21_0.<<EnableEventReceiveAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnableEventReceiveAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.SetMessageHandlerAsync(MessageHandler messageHandler, Object userContext, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.SetMessageHandlerAsync(MessageHandler messageHandler, Object userContext)
   at Microsoft.Azure.WebJobs.Extensions.EdgeHub.EdgeHubTriggerBindingProvider.TrySetEventDefaultHandlerAsync() in /home/vsts/work/1/s/edge-modules/functions/binding/src/Microsoft.Azure.WebJobs.Extensions.EdgeHub/EdgeHubTriggerBindingProvider.cs:line 68
   at Microsoft.Azure.WebJobs.Extensions.EdgeHub.EdgeHubTriggerBindingProvider.TryCreateAsync(TriggerBindingProviderContext context) in /home/vsts/work/1/s/edge-modules/functions/binding/src/Microsoft.Azure.WebJobs.Extensions.EdgeHub/EdgeHubTriggerBindingProvider.cs:line 36
   at Microsoft.Azure.WebJobs.Host.Triggers.CompositeTriggerBindingProvider.TryCreateAsync(TriggerBindingProviderContext context) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Triggers\CompositeTriggerBindingProvider.cs:line 22
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsyncCore(MethodInfo method, IFunctionIndexCollector index, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs:line 160
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsync(MethodInfo method, IFunctionIndexCollector index, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs:line 137
   --- End of inner exception stack trace ---
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsync(MethodInfo method, IFunctionIndexCollector index, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs:line 145
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexTypeAsync(Type type, IFunctionIndexCollector index, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs:line 73
fail: Function.EdgeHubTrigger-CSharp[0]
      Microsoft.Azure.WebJobs.Host: Error indexing method 'EdgeHubTrigger-CSharp'. Microsoft.Azure.Devices.Client: Transient network error occurred, please retry. System.Private.CoreLib: I/O error occurred.
```

SDK.Functions version 1.0.26 has a dependency on netstandard2.0, which will work in our dotnet 3.1 environment. In this PR I have:
- Switched SDK.Functions back to 1.0.26
- Published the functions filter module as a library with netstandard2.0
- Installed dotnet 2.1 on the build pipeline

For some reason, when building on linux it tries to find netstandard1.0 and throws an error when not found. Publishing works fine without netstandard1.0. This can be mitigated by installing dotnet2.1 on the build pipeline which is in this PR.